Refactor tests to use enzyme
AgileVentures/sfn-client pull request #100
Opened 2019-03-02 20:16 UTC by aonomike

- Refactor all tests to use enzyme
Fixes #98 
Co-authored-by: dhemmingson <danhemm@gmail.com>
Co-authored-by: javpet <javorkai.peter@gmail.com>

2019-03-03 17:43 UTC, FedericoEsparza requested changes
@aonomike @dhemmingson @javpet Amazing work! Thanks so much for putting in the work. 

It's a big PR replacing just about the whole test suite, so I have some thoughts and some requests.

Standby...

2019-03-04 15:40 UTC, aonomike commented
@FedericoEsparza this one was left specifically for you to review :)

2019-03-04 15:42 UTC, aonomike commented
> @aonomike @dhemmingson @javpet Amazing work! Thanks so much for putting in the work.
> 
> It's a big PR replacing just about the whole test suite, so I have some thoughts and some requests.
> 
> Standby...

2019-03-16 18:59 UTC, aonomike commented
maybe something that we've noticed is to refactor the `wrapped` to `wrapper` so as to keep up with the conventions

2019-03-16 19:05 UTC, FedericoEsparza commented
@aonomike This was part of my feedback that I wanted to add. I don't like `wrapped` nor `wrapper`, because it's not immediately clear, sometimes, what you are testing. I prefer using the name of the component, but very importantly LOWERCASED, otherwise it will throw hard to detect errors.

2019-03-16 19:22 UTC, aonomike commented
> @aonomike This was part of my feedback that I wanted to add. I don't like `wrapped` nor `wrapper`, because it's not immediately clear, sometimes, what you are testing. I prefer using the name of the component, but very importantly LOWERCASED, otherwise it will throw hard to detect errors.

Maybe to be the devil's advocate, is wrapper not used as a convention in the enzyme community?

2019-03-16 20:01 UTC, FedericoEsparza requested changes
@aonomike @javpet @dhemmingson Great work on this.

Please make all requested modifications.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/About/About.test.js
> +  })
The beforeEach hook is great forethought, but within the context of this PR, it prematurely might force you to remove the current test (unless you do something like create nested describe blocks).

**I believe the whole current test suite is removed within this PR, which is not good practice, because then replacing it with a simple test, like the following:**
 
```
expect(1+1).toEqual(2)
```

or something else meaningless, like that, could pass the CI and get merged in, if no one is reviewing the PRs properly.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/About/About.test.js
> +describe("<AboutContainer />", () => {
Please re-add this test

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformance/ArtistPerformance.test.js
> +let wrapped
Please move this to just above the `beforeEach` that it corresponds to, and rename it `artistPerformance`.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformance/ArtistPerformance.test.js
> -    const artistPerformance = <ArtistPerformance />;
Please re-add this test.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformance/ArtistPerformance.test.js
> +  })
Please modify `wrapper` to `artistPerformance`

You could add a nested describe block, but that will complicate things for now.

Just be sure to add the `let` right above and outside the `beforeEach`. This won't conflict with the `const` of the same name, because that is within it's own it function scope.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformance/ArtistPerformance.test.js
> +});
Please modify `wrapper` to `artistPerformance`

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformanceList/ArtistPerfomanceList.test.js
> +    beforeEach(()=>{
Please re-add test

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformanceList/ArtistPerfomanceList.test.js
> +let wrapped
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/About/About.test.js
> +    wrapped = shallow( < About / > )
Please remove beforeEach.

Please modify to `const about = shallow( <About/> )` and move down to just above the expectation on line 15.
You'll need to change `wrapped` to `about`.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformanceList/ArtistPerfomanceList.test.js
>  })
Please remove beforeEach.

Please modify to `const artistPerformanceList = shallow( < ArtistPerformanceList/> )` and move down to just above the expectation on line 16.
You'll need to change `wrapper` to `artistPerformanceList`.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/MoneyRaised/MoneyRaised.test.js
> -  });
Please re-add test, and kindly rename const to `moneyRaised`

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/MoneyRaised/MoneyRaised.test.js
> +let wrapped;
Please move this to just above the `beforeEach` that it corresponds to, and rename it `moneyRaised `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/MoneyRaised/MoneyRaised.test.js
> +  })
Please modify `wrapper` to `moneyRaised `

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/MoneyRaised/MoneyRaised.test.js
>  });
Please modify `wrapped` to `moneyRaised `

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/SupportedCauses/SupportedCauses.test.js
> +let wrapped
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/SupportedCauses/SupportedCauses.test.js
> -  });
Please re-add test

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artist/SupportedCauses/SupportedCauses.test.js
>  });
Please remove beforeEach.

Please modify this to `const supportedCauses = shallow( < SupportedCauses/> )` and move down to just above the expectation on line 13.
You'll need to change `wrapper` to `supportedCauses `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artists/Artists.test.js
> +let wrapped;
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artists/Artists.test.js
> -    const artists = <Artists/>;
Please re-add test

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Artists/Artists.test.js
>  });
Please remove beforeEach.
Modify to `const artists = shallow( < Artists/> )` and move down to just above the expectation on line 14.
You'll need to change `wrapped` to `artists `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Cause/Cause.test.js
> +let wrapped
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Cause/Cause.test.js
> +  })
Please remove beforeEach.

Modify to `const cause = shallow( < Cause/> )` and move down to just above the expectation on line 14.
You'll need to change `wrapper` to `cause `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Causes/Causes.test.js
> +let wrapped
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Performances/Performances.test.js
> +  })
Please remove beforeEach.

Modify to `const performances = shallow( < Performances/> )` and move down to just above the expectation on line 16.
You'll need to change `wrapper` to `performances `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Performances/Performances.test.js
> +let wrapped;
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Performance/Performance.test.js
> +  })
Please remove beforeEach.

Modify to `const performance = shallow( < Performance/> )` and move down to just above the expectation on line 16.
You'll need to change `wrapper` to `performance `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Performance/Performance.test.js
> +let wrapped;
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Home/Home.test.js
> +  })
Please remove beforeEach.

Modify to `const home = shallow( < Home/> )` and move down to just above the expectation on line 16.
You'll need to change `wrapper` to `home `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Home/Home.test.js
> +let wrapped;
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Header/Header.test.js
> +  })
Please remove beforeEach.

Modify to `const header = shallow( < Header/> )` and move down to just above the expectation on line 16.
You'll need to change `wrapper` to `header `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Header/Header.test.js
> +let wrapped;
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Contact/Contact.test.js
> +
Please remove beforeEach.

Modify to `const contact = shallow( < Contact/> )` and move down to just above the expectation on line 15.
You'll need to change `wrapper` to `contact `.

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Contact/Contact.test.js
> +let wrapped;
Please remove let

2019-03-16 20:01 UTC, FedericoEsparza commented on src/components/Causes/Causes.test.js
> +});
Please remove beforeEach.

Modify to `const causes = shallow( < Causes/> )` and move down to just above the expectation on line 14.
You'll need to change `wrapper` to `causes `.

2019-03-16 20:57 UTC, FedericoEsparza requested changes
@aonomike @dhemmingson @javpet Review updated.

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artist/Artist.test.js
>  });
Please modify `wrapped` to `artist`

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/About/About.test.js
> +let wrapper;
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformanceList/ArtistPerfomanceList.test.js
> +let wrapper
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Performances/Performances.test.js
> +let wrapper;
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Performance/Performance.test.js
> +let wrapper;
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Home/Home.test.js
> +let wrapper;
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Header/Header.test.js
> +let wrapper;
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Contact/Contact.test.js
> +let wrapper;
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Causes/Causes.test.js
> +let wrapper
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Cause/Cause.test.js
> +let wrapper
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artist/SupportedCauses/SupportedCauses.test.js
> +let wrapper
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artists/Artists.test.js
>    });
Please remove beforeEach.

Modify to `const artists = shallow( < Artists/> )` and move down to just above the expectation on line 16.
You'll need to change `wrapper` to `artists `.

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artists/Artists.test.js
> +let wrapper;
Please remove let

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artist/MoneyRaised/MoneyRaised.test.js
> +});
You'll need to change `wrapper` to `moneyRaised `.

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformance/ArtistPerformance.test.js
> +let wrapper
Please move `let` to just above `beforeEach` and rename to `artistPerformance `

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artist/MoneyRaised/MoneyRaised.test.js
> +let wrapper;
Please move `let` to just above `beforeEach` and rename to `moneyRaised`

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artist/Artist.test.js
> +let wrapper;
Please move `let` to just above `beforeEach` and rename to `artist `

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Artist/ArtistPerformanceList/ArtistPerfomanceList.test.js
> -    })
Please re-add this test

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Cause/Cause.test.js
> -  });
Please re-add this test

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Causes/Causes.test.js
> -  });
Please re-add this test

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Contact/Contact.test.js
> -  });
Please re-add this test

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Header/Header.test.js
> -  });
Please re-add this test

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Home/Home.test.js
> -  });
Please re-add this test

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Performance/Performance.test.js
> -  });
Please re-add this test

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/Performances/Performances.test.js
> -});
Please re-add this test

2019-03-16 20:57 UTC, FedericoEsparza commented on src/components/About/About.test.js
> +  })
Please remove beforeEach.

Please modify to `const about = shallow( < About/> )` and move down to just above the expectation on line 17.
You'll need to change `wrapper` to `about`.

2019-03-23 18:16 UTC, FedericoEsparza approved these changes
@aonomike @javpet @dhemmingson Made a few modifications re-adding the beforeEach whenever you actually did have multiple tests using the wrapper.

Not the greatest fan of the use of the word `Wrapper`

I would prefer `componentName` instead, and as requested, but I guess I did say I was ok with `componentNameWrapper`, so I'll go ahead and approve.

**Thanks for your patience on the reviews, and for taking the time to make the modifications.**

I really appreciate it! 🥇 👍

2019-03-23 18:17 UTC, merged