added responsive nav bar
AgileVentures/sfn-client pull request #181
Opened 2019-04-23 03:21 UTC by jmpainter

- Added Layout container with nav bar state
- moved Header and Footer into components/Layout
- created NavBar component

tests have not been updated yet

2019-04-24 02:03 UTC, SherSpock commented
While it seems we don't have anything in the PR review process that prevents it, I'm exercising the right not to review this until the build is green. That shouldn't prevent anyone else who wants to do so though

2019-04-24 02:32 UTC, FedericoEsparza commented
Yep. Reviewing a PR can be potentially time-consuming, so I don't like to even look at PRs that are failing CI or labeled as [WIP].

UNLESS it's a languishing PR, not going anywhere, or creating a pile-up or bottleneck, in which case I might jump **in--and I would encourage others to feel free--to try to fix the PR, preferably with a PR to the original PR's branch.** Just be respectful of the contributor's effort. 

While I do want to adhere to AV's mission to help developers learn to program and gain experience on real projects, and I think we go out of our way to help foster that environment in Championer projects, AV's partnership with Championer doesn't preclude us from helping to move things along, when called for.

@jmpainter I assume you got this under control, but let me know if you get stuck.

2019-04-24 02:35 UTC, jmpainter commented
I updated the tests for a passing build. I'll add additional tests once the basic approach of this PR is confirmed.

2019-04-29 06:21 UTC, FedericoEsparza requested changes
@jmpainter You're doing an amazing job, heading in the right direction, Josh. 

I like how the mobile dropdown mobileMenu looks.

I think we'll want to figure out a solution for not having the NavLinks stack, as the window narrows on a desktop, though.

Let me know if you have trouble trying to fix this.

See the line comments about removing the constructor for the `Layout` container. This will cause the linter to complain, but it should be ok, once ticket #188 is merged, and you pull from upstream.

Please, also move the `NavBar` component folder into the `src/components/Layout/` folder.

**Keep at it! You're doing great work with this PR.**

2019-04-29 06:21 UTC, FedericoEsparza commented on src/containers/Layout/Layout.js
> +      <div className="main-container">
I think you'll want remove `className="main-container"` in order for the Header to reach the full width of the page.

2019-04-29 06:21 UTC, FedericoEsparza commented on src/components/App.js
> +        <main className="grid">
I think you'll want to re-add the `main-container` class to `<main className="grid">` here.

2019-04-29 06:21 UTC, FedericoEsparza commented on src/components/App.js
You can move the Layout down with the other components.

2019-04-29 06:21 UTC, FedericoEsparza commented on src/containers/Layout/Layout.js
> +  }
Let's get rid of the constructor, and use the newer state initializer syntax, with or without the semicolon, as so:
<img width="379" alt="Screen Shot 2019-04-26 at 11 21 15 PM" src="https://user-images.githubusercontent.com/11988089/56878542-2609af00-6a44-11e9-8c37-237dec1867f7.png">

2019-04-29 06:21 UTC, FedericoEsparza commented on src/components/Layout/Header/header.scss
> +  background-color: $primary-color-darkblue;
You'll want to keep this as `$primary-color-darkblue-lighter;`

2019-04-29 06:26 UTC, FedericoEsparza commented on src/containers/Layout/Layout.js
> +  }
Please refactor to initialize with an arrow function, as so:
<img width="669" alt="Screen Shot 2019-04-28 at 11 57 47 PM" src="https://user-images.githubusercontent.com/11988089/56878236-9c0d1680-6a42-11e9-9298-83576e6edd90.png">
Doing so will keep us from needing to bind `this` for the function, and we can use the state initializer syntax, without a constructor, which is more clean.

2019-04-29 19:48 UTC, jmpainter commented
Thanks for your feedback on this PR. I made the requested changes and added more tests. I'm keeping the breakpoints for the NavBar consistent with those in _layout.scss. The build is failing CI due to eslint.

2019-05-12 08:16 UTC, FedericoEsparza approved these changes

2019-05-12 08:17 UTC, merged

2019-05-12 08:26 UTC, FedericoEsparza commented
@jmpainter Absolutely excellent work, Josh.

I know it was a lot of work, but it's looking great. And you fixed all the requested changes.

I went ahead and re-added the navlinks to the footer, and updated the copyright message:
<img width="1261" alt="Screen Shot 2019-05-12 at 3 15 41 AM" src="https://user-images.githubusercontent.com/11988089/57579639-b5f82180-7464-11e9-9694-8e89b9782dfb.png">

We'll have to figure out a way to make them more mobile friendly, but I didn't want them to get left behind.

I think we'll end up going with a more vertically stacked footer, with more links, in the end.

Excellent job wrangling the mobile header to play nice with the desktop header and with the whole reconstructed Layout with props for the header and footer:
<img width="502" alt="Screen Shot 2019-05-12 at 3 22 48 AM" src="https://user-images.githubusercontent.com/11988089/57579706-73831480-7465-11e9-81e1-a24fa9f99ed1.png">